name: Gh-Pages

on:
  push:
    branches:
      - jm-portfolio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
#      - uses: erickzanardo/flutter-gh-pages@v3
      - uses: david-legend/flutter-gh-pages
